language: java

script: ./gradlew build

deploy:
  provider: releases
  api_key:  
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/**/*
  skip_cleanup: true
  on:
    tags: true
              - name: Gradle Dependency Submission
                uses: mikepenz/gradle-dependency-submission@v1.0.0
            
